

import CookieContextProvider from '@/context/CookieContextProvider'
import '../styles/globals.css'
import { Toaster } from 'react-hot-toast'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
      <body >
        <CookieContextProvider>
          {children}
          <Toaster position="top-left" />
        </CookieContextProvider>
      </body>
    </html>
  )
}
